// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB84ZQqxiZdRgmoBq704rc-KWHSkuaKK44',
    appId: '1:301397935757:web:8dd5167cc9c1bd25f084c4',
    messagingSenderId: '301397935757',
    projectId: 'stride-test-8efbf',
    authDomain: 'stride-test-8efbf.firebaseapp.com',
    storageBucket: 'stride-test-8efbf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvHBVZM7J6XhJAUlQ0oDtP8XDOCTMNxn0',
    appId: '1:301397935757:android:89b71e1da183fa80f084c4',
    messagingSenderId: '301397935757',
    projectId: 'stride-test-8efbf',
    storageBucket: 'stride-test-8efbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjD7E-S2ql_Nzq_nqLJ0RL3XoMt1Mrn3o',
    appId: '1:301397935757:ios:e66b74b3ee4eebe6f084c4',
    messagingSenderId: '301397935757',
    projectId: 'stride-test-8efbf',
    storageBucket: 'stride-test-8efbf.appspot.com',
    iosBundleId: 'com.example.eeasyRfid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjD7E-S2ql_Nzq_nqLJ0RL3XoMt1Mrn3o',
    appId: '1:301397935757:ios:563fa658203fd875f084c4',
    messagingSenderId: '301397935757',
    projectId: 'stride-test-8efbf',
    storageBucket: 'stride-test-8efbf.appspot.com',
    iosBundleId: 'com.example.eeasyRfid.RunnerTests',
  );
}
